USE HR_ATTIRITION;
SHOW TABLES;
SELECT * FROM HR;
SELECT COUNT(EMPID) FROM HR;
SELECT ATTRITION,COUNT(ATTRITION) FROM HR GROUP BY ATTRITION;
SELECT DEPARTMENT,ATTRITION,COUNT(ATTRITION) FROM HR GROUP BY DEPARTMENT,ATTRITION ORDER BY ATTRITION DESC;
-- Sales	Yes	92
-- Research & Development	Yes	133
-- Human Resources	Yes	12
-- Research & Development	No	828
-- Sales	No	354
-- Human Resources	No	51