USE SALESDETAILS;
SHOW TABLES;
SELECT * FROM SALESDETAILS;
SELECT *,AMOUNT*QUANTITY AS SP FROM SALESDETAILS;
SELECT SUM(AMOUNT+PROFIT) AS FINAL_PROFIT FROM SALESDETAILS;
-- 36963
SELECT * FROM salesdetails WHERE PROFIT<1;
SELECT COUNT(*) FROM salesdetails WHERE PROFIT<1;
-- 576 DATA INDICATES LOSSES
SELECT SUM(AMOUNT+PROFIT) FROM salesdetails WHERE PROFIT<1;
-- -38079 RUPEES LOSS
